Updated setup and Introduction to refer to Apptainer, to expand instr…
hsf-training/hsf-training-singularity-webpage pull request #56
Opened 2022-09-07 14:29 UTC by mambelli

Updated setup and Introduction to refer to Apptainer, expand instructions, and clarify differences between Apptainer, Docker, and other Singularity versions.

This work was part of the 2022-01-06 hackathon:
* Expand the setup, issue #2 (I referred to existing instructions)
* Add: Pros/cons/Differences/Similarities between docker/singularity, Fixes #6 
* Singularity or Apptainer?, Fixes #27 - before the end of September Apptainer is expected to replace Singularity in EPEL. At a later time, we'll have to think about switching the command name and environment variables.

2022-09-07 14:32 UTC, amanmdesai commented
pre-commit failure is due to this

_episodes/01-introduction.md:47: withot ==> without
setup.md:6: deatils ==> details

2022-09-07 14:40 UTC, mambelli commented
> pre-commit failure is due to this
> 
> _episodes/01-introduction.md:47: withot ==> without setup.md:6: deatils ==> details

Fixed, thanks

2022-09-07 20:27 UTC, michmx commented
Thanks a lot, @mambelli ! Very nice explanation of Singularity --> Apptainer. 

I just found a typo. Besides that, this PR is ready to go.

2022-09-07 20:28 UTC, michmx requested changes

2022-09-07 20:28 UTC, michmx commented on _episodes/01-introduction.md
> +so they are computationally heavier to run, require bigger files when distributed and are less flexible then containers,
typo: then --> than

2022-09-08 03:36 UTC, mambelli commented on _episodes/01-introduction.md
> +so they are computationally heavier to run, require bigger files when distributed and are less flexible then containers,
updated, thanks

2022-09-08 06:09 UTC, michmx approved these changes

2022-09-08 06:11 UTC, merged