Add bonus episode
hsf-training/hsf-training-singularity-webpage pull request #62
Opened 2022-09-19 16:58 UTC by amanmdesai

Tasks to do:
- [ ] Add keypoints
- [ ]  feedback regarding python packages to be installed (currently several packages are included)  

Hopefully this commit:
* Closes #10
* Closes #13 
* Closes #19 

Pinging @klieret  @michmx for review

2022-09-19 17:05 UTC, amanmdesai commented
FYI
The episodes uses the code/def files which were tested in:
* https://github.com/amanmdesai/singularity-scikit-hep
* https://github.com/amanmdesai/hello-world-singularity

2022-09-19 20:38 UTC, klieret commented
(Marked as draft because of the todo notes)

2022-09-20 16:56 UTC, amanmdesai commented
added keypoints,

since tests are successful, task two is completed (confirmed)

2022-09-20 16:56 UTC, amanmdesai commented
@klieret  @michmx  this PR is now ready for review

2022-10-04 15:19 UTC, michmx requested changes
Hi @amanmdesai . Thanks a lot for your very valuable contribution and very sorry for taking so long in the review (it has been a busy season for me). 
I left a couple of comments, but let me say the quality of your material is already very good. Thanks a lot.

2022-10-04 15:19 UTC, michmx commented on _episodes/08-bonus-episode.md
> +_Why is installation over several layers advantageous?_
Instead of leaving the question open, you can add it as an exercise (with the `{: .challenge}` environment) providing an answer.

2022-10-04 15:19 UTC, michmx commented on _episodes/08-bonus-episode.md
> +It is possible to publish singularity images with GitHub packages. To do so, one needs to use GitHub CI/CD. A step-by-step guide is presented here.
Leave a comment for students not familiar with CI/CD, sharing the link to our training material about it:
https://hsf-training.github.io/hsf-training-cicd-github/

2022-10-04 16:13 UTC, amanmdesai commented on _episodes/08-bonus-episode.md
> +It is possible to publish singularity images with GitHub packages. To do so, one needs to use GitHub CI/CD. A step-by-step guide is presented here.
Thanks for your comment. 
I have included link to CI/CD in the pre-requisite in the beginning of this episode. 

....
 Some knowledge of GitHub CI/CD [HSF Github CI/CD Lesson](https://github.com/hsf-training/hsf-training-cicd-github)
{: .prereq}

2022-10-04 16:26 UTC, amanmdesai commented on _episodes/08-bonus-episode.md
> +_Why is installation over several layers advantageous?_
Thanks. implemented in the latest commit.

2022-10-04 16:33 UTC, amanmdesai commented
Hi @michmx Thanks for your comments.  I have implemented them in the episode. Please let me know if futher changes are required.

2022-10-04 17:55 UTC, michmx approved these changes

2022-10-04 18:05 UTC, klieret approved these changes
Looks very good to me except for the tiny typo above ;)

2022-10-04 18:05 UTC, klieret commented on _episodes/08-bonus-episode.md
> +Python packages can be installed using a Singularity image. The following example illustrates how to write an definition file for building an image containing python packages.
typo: a definition

2022-10-04 18:42 UTC, amanmdesai commented on _episodes/08-bonus-episode.md
> +Python packages can be installed using a Singularity image. The following example illustrates how to write an definition file for building an image containing python packages.
thanks for the comment. Implemented it.

2022-10-04 18:44 UTC, merged

2022-10-04 18:47 UTC, amanmdesai commented
thanks @klieret  and @michmx for reviewing!